// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB13TtdbtOLkhlFgWekzOMfNl-SDu4IkZ0',
    appId: '1:837809811184:web:c214f671217617171fdc35',
    messagingSenderId: '837809811184',
    projectId: 'nexa-app-2f893',
    authDomain: 'nexa-app-2f893.firebaseapp.com',
    storageBucket: 'nexa-app-2f893.firebasestorage.app',
    measurementId: 'G-HZJVB4PVF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARlC8-rQJgjOFTUzPBQRHoiOx9Oi4rGRc',
    appId: '1:837809811184:android:8475cde9f55f8a021fdc35',
    messagingSenderId: '837809811184',
    projectId: 'nexa-app-2f893',
    storageBucket: 'nexa-app-2f893.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAswWBuLqCoLxi0n_8-UynD-VBBT81aXcY',
    appId: '1:837809811184:ios:6841767fe515851c1fdc35',
    messagingSenderId: '837809811184',
    projectId: 'nexa-app-2f893',
    storageBucket: 'nexa-app-2f893.firebasestorage.app',
    iosBundleId: 'com.example.nexaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAswWBuLqCoLxi0n_8-UynD-VBBT81aXcY',
    appId: '1:837809811184:ios:6841767fe515851c1fdc35',
    messagingSenderId: '837809811184',
    projectId: 'nexa-app-2f893',
    storageBucket: 'nexa-app-2f893.firebasestorage.app',
    iosBundleId: 'com.example.nexaapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB13TtdbtOLkhlFgWekzOMfNl-SDu4IkZ0',
    appId: '1:837809811184:web:2b2d3eb9f6cda45a1fdc35',
    messagingSenderId: '837809811184',
    projectId: 'nexa-app-2f893',
    authDomain: 'nexa-app-2f893.firebaseapp.com',
    storageBucket: 'nexa-app-2f893.firebasestorage.app',
    measurementId: 'G-HMS5LBTG76',
  );
}
